version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      cloudflare-tooling:
        patterns:
          - "wrangler"
          - "@cloudflare/workers-types"
      npm-minor-and-patch-updates:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      npm-major-updates:
        update-types:
          - major
        patterns:
          - "*"
      all-npm-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
